source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/myiOSComponent/myRepo.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'TKNetworking_Example' do
  pod 'TKNetworking', :path => '../'

  target 'TKNetworking_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  pod 'TKNetwork', '~> 0.0.1'
  end
end
